In [1]:
!pip uninstall numpy -y

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4

In [3]:
!pip install numpy==1.26.4

Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.4

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.17.1 which is incompatible.
mlxtend 0.24.0 requires numpy>=2.3.5, but you have numpy 1.26.4 which is incompatible.
streamlit 1.37.1 requires pandas<3,>=1.3.0, but you have pandas 3.0.3 which is incompatible.
streamlit 1.37.1 requires protobuf<6,>=3.20, but you have protobuf 7.35.0 which is incompatible.

In [5]:
!pip install tensorflow --upgrade

Requirement already satisfied: tensorflow in c:\users\aquib\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (7.35.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (1.80.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (1.26.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (3.11.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\aquib\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\aquib\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in c:\users\aquib\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (13.7.1)
Requirement already satisfied: namex in c:\users\aquib\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\aquib\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aquib\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aquib\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aquib\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aquib\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\aquib\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\aquib\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\aquib\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.0)

In [7]:
import tensorflow as tf

print(tf.__version__)

2.21.0

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [57]:
## EDA

In [11]:
df = pd.read_csv("Alphabets_data.csv")
df.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [13]:
df.shape

(20000, 17)

In [15]:
df.info

<bound method DataFrame.info of       letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  \
0          T     2     8      3       5      1     8    13      0      6
1          I     5    12      3       7      2    10     5      5      4
2          D     4    11      6       8      6    10     6      2      6
3          N     7    11      6       6      3     5     9      4      6
4          G     2     1      3       1      1     8     6      6      6
...      ...   ...   ...    ...     ...    ...   ...   ...    ...    ...
19995      D     2     2      3       3      2     7     7      7      6
19996      C     7    10      8       8      4     4     8      6      9
19997      T     6     9      6       7      5     6    11      3      7
19998      S     2     3      4       2      1     8     7      2      6
19999      A     4     9      6       6      2     9     5      3      1

       xybar  x2ybar  xy2bar  xedge  xedgey  yedge  yedgex
0          6      10       8      0       8      0       8
1         13       3       9      2       8      4      10
2         10       3       7      3       7      3       9
3          4       4      10      6      10      2       8
4          6       5       9      1       7      5      10
...      ...     ...     ...    ...     ...    ...     ...
19995      6       6       4      2       8      3       7
19996     12       9      13      2       9      3       7
19997     11       9       5      2      12      2       4
19998     10       6       8      1       9      5       8
19999      8       1       8      2       7      2       8

[20000 rows x 17 columns]>

In [17]:
df.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [19]:
df.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [21]:
##-> There are no null values present in the dataset

In [23]:
df.columns

Index(['letter', 'xbox', 'ybox', 'width', 'height', 'onpix', 'xbar', 'ybar',
       'x2bar', 'y2bar', 'xybar', 'x2ybar', 'xy2bar', 'xedge', 'xedgey',
       'yedge', 'yedgex'],
      dtype='str')

In [25]:
X = df.drop('letter', axis=1)
y = df['letter']

In [27]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [29]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [61]:
##-> The values are now scaled and categorical are tranformed into numeric values.

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [63]:
## Model Training

In [42]:
model = Sequential()

# Hidden layer
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))

# Output layer
model.add(Dense(len(np.unique(y)), activation='softmax'))

C:\Users\aquib\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [44]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [46]:
history = model.fit(X_train,y_train,epochs=20,batch_size=32,validation_split=0.2)

Epoch 1/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4334 - loss: 2.1748 - val_accuracy: 0.6775 - val_loss: 1.4149
Epoch 2/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7083 - loss: 1.1571 - val_accuracy: 0.7419 - val_loss: 1.0036
Epoch 3/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7627 - loss: 0.8999 - val_accuracy: 0.7731 - val_loss: 0.8488
Epoch 4/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7909 - loss: 0.7736 - val_accuracy: 0.7959 - val_loss: 0.7527
Epoch 5/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8086 - loss: 0.6891 - val_accuracy: 0.8156 - val_loss: 0.6797
Epoch 6/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8259 - loss: 0.6270 - val_accuracy: 0.8266 - val_loss: 0.6239
Epoch 7/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8396 - loss: 0.5765 - val_accuracy: 0.8369 - val_loss: 0.5812
Epoch 8/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8510 - loss: 0.5357 - val_accuracy: 0.8453 - val_loss: 0.5450
Epoch 9/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8613 - loss: 0.5000 - val_accuracy: 0.8544 - val_loss: 0.5163
Epoch 10/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8687 - loss: 0.4700 - val_accuracy: 0.8619 - val_loss: 0.4854
Epoch 11/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8766 - loss: 0.4426 - val_accuracy: 0.8725 - val_loss: 0.4640
Epoch 12/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8849 - loss: 0.4197 - val_accuracy: 0.8731 - val_loss: 0.4445
Epoch 13/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8885 - loss: 0.3995 - val_accuracy: 0.8781 - val_loss: 0.4239
Epoch 14/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8938 - loss: 0.3807 - val_accuracy: 0.8844 - val_loss: 0.4092
Epoch 15/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8977 - loss: 0.3634 - val_accuracy: 0.8841 - val_loss: 0.3976
Epoch 16/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9006 - loss: 0.3492 - val_accuracy: 0.8869 - val_loss: 0.3833
Epoch 17/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9053 - loss: 0.3341 - val_accuracy: 0.8928 - val_loss: 0.3707
Epoch 18/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9062 - loss: 0.3221 - val_accuracy: 0.8934 - val_loss: 0.3605
Epoch 19/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9114 - loss: 0.3103 - val_accuracy: 0.8941 - val_loss: 0.3530
Epoch 20/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9139 - loss: 0.2994 - val_accuracy: 0.8966 - val_loss: 0.3447

In [38]:
history = model.fit(X_train,y_train,epochs=20,batch_size=32,validation_split=0.2)

Epoch 1/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9160 - loss: 0.2857 - val_accuracy: 0.9000 - val_loss: 0.3289
Epoch 2/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9202 - loss: 0.2769 - val_accuracy: 0.9038 - val_loss: 0.3195
Epoch 3/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9196 - loss: 0.2690 - val_accuracy: 0.9022 - val_loss: 0.3132
Epoch 4/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9242 - loss: 0.2617 - val_accuracy: 0.9056 - val_loss: 0.3080
Epoch 5/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9243 - loss: 0.2546 - val_accuracy: 0.9062 - val_loss: 0.3021
Epoch 6/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9266 - loss: 0.2474 - val_accuracy: 0.9100 - val_loss: 0.2945
Epoch 7/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9268 - loss: 0.2419 - val_accuracy: 0.9094 - val_loss: 0.2898
Epoch 8/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9292 - loss: 0.2352 - val_accuracy: 0.9078 - val_loss: 0.2867
Epoch 9/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9322 - loss: 0.2290 - val_accuracy: 0.9103 - val_loss: 0.2806
Epoch 10/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9341 - loss: 0.2248 - val_accuracy: 0.9106 - val_loss: 0.2786
Epoch 11/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9336 - loss: 0.2189 - val_accuracy: 0.9144 - val_loss: 0.2752
Epoch 12/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9369 - loss: 0.2143 - val_accuracy: 0.9184 - val_loss: 0.2696
Epoch 13/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9380 - loss: 0.2103 - val_accuracy: 0.9156 - val_loss: 0.2660
Epoch 14/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9392 - loss: 0.2057 - val_accuracy: 0.9169 - val_loss: 0.2608
Epoch 15/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9402 - loss: 0.2016 - val_accuracy: 0.9169 - val_loss: 0.2588
Epoch 16/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9418 - loss: 0.1973 - val_accuracy: 0.9203 - val_loss: 0.2573
Epoch 17/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9422 - loss: 0.1936 - val_accuracy: 0.9184 - val_loss: 0.2574
Epoch 18/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9419 - loss: 0.1901 - val_accuracy: 0.9225 - val_loss: 0.2524
Epoch 19/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9457 - loss: 0.1865 - val_accuracy: 0.9169 - val_loss: 0.2506
Epoch 20/20
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9454 - loss: 0.1838 - val_accuracy: 0.9228 - val_loss: 0.2454

In [39]:
# Predict probabilities
y_pred_prob = model.predict(X_test)

# Convert probabilities to class labels
y_pred = np.argmax(y_pred_prob, axis=1)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Classification Report
print(classification_report(y_test, y_pred))

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy: 0.928
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       149
           1       0.84      0.92      0.88       153
           2       0.92      0.88      0.90       137
           3       0.92      0.91      0.91       156
           4       0.91      0.91      0.91       141
           5       0.90      0.92      0.91       140
           6       0.92      0.88      0.89       160
           7       0.88      0.78      0.82       144
           8       0.96      0.91      0.93       146
           9       0.91      0.96      0.93       149
          10       0.84      0.91      0.87       130
          11       0.94      0.95      0.95       155
          12       0.94      0.95      0.94       168
          13       0.92      0.91      0.92       151
          14       0.90      0.94      0.92       145
          15       0.97      0.92      0.95       173
          16       0.96      0.95      0.95       166
          17       0.87      0.89      0.88       160
          18       0.94      0.95      0.95       171
          19       0.99      0.91      0.95       163
          20       0.96      0.95      0.95       183
          21       0.94      0.95      0.95       158
          22       0.97      0.95      0.96       148
          23       0.94      0.99      0.96       154
          24       0.96      0.99      0.97       168
          25       0.97      0.93      0.95       132

    accuracy                           0.93      4000
   macro avg       0.93      0.93      0.93      4000
weighted avg       0.93      0.93      0.93      4000

In [51]:
results = []

neurons_list = [64, 128]
epochs_list = [20, 30]
batch_sizes = [16, 32]

for neurons in neurons_list:
    for epochs in epochs_list:
        for batch_size in batch_sizes:

            from tensorflow.keras import Input

            model = Sequential([
                Input(shape=(X_train.shape[1],)),
                Dense(neurons, activation='relu'),
                Dense(len(np.unique(y)), activation='softmax')
            ])

            model.compile(
                optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy']
            )

            history = model.fit(
                X_train,
                y_train,
                epochs=epochs,
                batch_size=batch_size,
                validation_split=0.2,
                verbose=0
            )

            val_acc = max(history.history['val_accuracy'])

            results.append({
                'Neurons': neurons,
                'Epochs': epochs,
                'Batch Size': batch_size,
                'Validation Accuracy': val_acc
            })

In [52]:
results_df = pd.DataFrame(results)

results_df.sort_values(
    by='Validation Accuracy',
    ascending=False,
    inplace=True
)

results_df

   Neurons  Epochs  Batch Size  Validation Accuracy
6      128      30          16             0.944062
7      128      30          32             0.941875
4      128      20          16             0.938438
2       64      30          16             0.929375
5      128      20          32             0.928750
3       64      30          32             0.916562
0       64      20          16             0.915000
1       64      20          32             0.904063

In [53]:
best_model = Sequential()

best_model.add(Dense(
    128,
    activation='relu',
    input_shape=(X_train.shape[1],)
))

best_model.add(Dense(
    len(np.unique(y)),
    activation='softmax'
))

best_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

best_model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/30

C:\Users\aquib\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.6001 - loss: 1.5393 - val_accuracy: 0.7506 - val_loss: 0.9499
Epoch 2/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7879 - loss: 0.7763 - val_accuracy: 0.8050 - val_loss: 0.6987
Epoch 3/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8314 - loss: 0.6020 - val_accuracy: 0.8381 - val_loss: 0.5717
Epoch 4/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8579 - loss: 0.4985 - val_accuracy: 0.8578 - val_loss: 0.4918
Epoch 5/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8791 - loss: 0.4292 - val_accuracy: 0.8737 - val_loss: 0.4315
Epoch 6/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8939 - loss: 0.3771 - val_accuracy: 0.8891 - val_loss: 0.3869
Epoch 7/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9058 - loss: 0.3376 - val_accuracy: 0.9038 - val_loss: 0.3502
Epoch 8/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9144 - loss: 0.3046 - val_accuracy: 0.9087 - val_loss: 0.3245
Epoch 9/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9203 - loss: 0.2766 - val_accuracy: 0.9091 - val_loss: 0.3069
Epoch 10/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9266 - loss: 0.2546 - val_accuracy: 0.9216 - val_loss: 0.2880
Epoch 11/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9329 - loss: 0.2343 - val_accuracy: 0.9253 - val_loss: 0.2710
Epoch 12/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9380 - loss: 0.2174 - val_accuracy: 0.9247 - val_loss: 0.2633
Epoch 13/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9405 - loss: 0.2034 - val_accuracy: 0.9278 - val_loss: 0.2545
Epoch 14/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9452 - loss: 0.1917 - val_accuracy: 0.9337 - val_loss: 0.2405
Epoch 15/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9473 - loss: 0.1794 - val_accuracy: 0.9325 - val_loss: 0.2321
Epoch 16/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9491 - loss: 0.1699 - val_accuracy: 0.9341 - val_loss: 0.2281
Epoch 17/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9531 - loss: 0.1598 - val_accuracy: 0.9337 - val_loss: 0.2222
Epoch 18/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9561 - loss: 0.1534 - val_accuracy: 0.9356 - val_loss: 0.2209
Epoch 19/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9576 - loss: 0.1436 - val_accuracy: 0.9381 - val_loss: 0.2077
Epoch 20/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9613 - loss: 0.1369 - val_accuracy: 0.9372 - val_loss: 0.2145
Epoch 21/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9634 - loss: 0.1304 - val_accuracy: 0.9388 - val_loss: 0.1998
Epoch 22/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9646 - loss: 0.1244 - val_accuracy: 0.9347 - val_loss: 0.2060
Epoch 23/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9666 - loss: 0.1181 - val_accuracy: 0.9375 - val_loss: 0.1949
Epoch 24/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9681 - loss: 0.1117 - val_accuracy: 0.9397 - val_loss: 0.1946
Epoch 25/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9689 - loss: 0.1092 - val_accuracy: 0.9381 - val_loss: 0.1908
Epoch 26/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9717 - loss: 0.1035 - val_accuracy: 0.9409 - val_loss: 0.1881
Epoch 27/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9713 - loss: 0.1000 - val_accuracy: 0.9444 - val_loss: 0.1831
Epoch 28/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9743 - loss: 0.0962 - val_accuracy: 0.9375 - val_loss: 0.1847
Epoch 29/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9748 - loss: 0.0910 - val_accuracy: 0.9444 - val_loss: 0.1751
Epoch 30/30
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9755 - loss: 0.0885 - val_accuracy: 0.9409 - val_loss: 0.1792

In [65]:
y_pred_prob = best_model.predict(X_test)

y_pred = np.argmax(y_pred_prob, axis=1)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Accuracy: 0.9475
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       149
           1       0.91      0.94      0.92       153
           2       0.93      0.94      0.94       137
           3       0.94      0.89      0.91       156
           4       0.92      0.95      0.93       141
           5       0.92      0.96      0.94       140
           6       0.93      0.94      0.93       160
           7       0.89      0.86      0.87       144
           8       0.98      0.92      0.95       146
           9       0.92      0.97      0.94       149
          10       0.86      0.93      0.89       130
          11       0.97      0.95      0.96       155
          12       0.97      0.99      0.98       168
          13       0.97      0.94      0.95       151
          14       0.91      0.96      0.93       145
          15       0.98      0.94      0.96       173
          16       0.99      0.95      0.97       166
          17       0.89      0.93      0.91       160
          18       0.97      0.97      0.97       171
          19       0.96      0.95      0.96       163
          20       0.97      0.96      0.97       183
          21       0.97      0.94      0.96       158
          22       0.98      0.97      0.98       148
          23       0.94      0.97      0.96       154
          24       0.98      0.98      0.98       168
          25       0.98      0.92      0.95       132

    accuracy                           0.95      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.95      0.95      0.95      4000

In [67]:
##-> The Artificial Neural Network (ANN) model was successfully implemented for the classification of alphabet data.
##-> Initial data exploration and preprocessing, including handling missing values and feature normalization, improved the quality of the input data.